ALTER TABLE MEDICINE_IN_PRES
ADD CONSTRAINT FK_MEDINPRES_PRESCRIPTION
FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPITON(PRESCRIPTION_ID);

ALTER TABLE MEDICINE_IN_PRES
ADD CONSTRAINT FK_MEDINPRES_MEDICINE
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID);

ALTER TABLE PRESCRIPITON
ADD CONSTRAINT FK_PRESCRIPTION_APPOINTMENT
FOREIGN KEY (APPOINTMENT_ID, TREATMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID, TREATMENT_ID);

ALTER TABLE INVOICE
ADD CONSTRAINT FK_INVOICE_APPOINTMENT
FOREIGN KEY (APPOINTMENT_ID, TREATMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID, TREATMENT_ID);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_TREATMENT
FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID);

ALTER TABLE TREATMENT
ADD CONSTRAINT FK_TREATMENT_PATIENT
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID);

ALTER TABLE TREATMENT
ADD CONSTRAINT FK_TREATMENT_DENTIST
FOREIGN KEY (DENTIST_ID) REFERENCES DENTIST(DENTIST_ID);

ALTER TABLE TREATMENT
ADD CONSTRAINT FK_TREATMENT_ASSISTANT
FOREIGN KEY (ASSISTANT_ID) REFERENCES DENTIST(DENTIST_ID);

ALTER TABLE REQUEST
ADD CONSTRAINT FK_REQUEST_PATIENT
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID);

ALTER TABLE APPROVED_REQUEST
ADD CONSTRAINT FK_APPREQ_REQUEST
FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST(REQUEST_ID);

ALTER TABLE APPROVED_REQUEST
ADD CONSTRAINT FK_APPREQ_STAFF
FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE SCHEDULE_FOR_EMPLOYEE
ADD CONSTRAINT FK_SCHEDULE_DENTIST
FOREIGN KEY (EMPLOYEE_ID) REFERENCES DENTIST(DENTIST_ID);

ALTER TABLE SCHEDULE_FOR_EMPLOYEE
ADD CONSTRAINT FK_SCHEDULE_STAFF
FOREIGN KEY (EMPLOYEE_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE SCHEDULE_FOR_EMPLOYEE
ADD CONSTRAINT FK_SCHEDULE_DATE
FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(DATE);